// scheduler-4.3.8-trial/examples/frameworks/angular/basic/src/app/app.component.ts
/**
 * App component script
 */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { Scheduler } from '@bryntum/scheduler/scheduler.lite.umd.js';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

    public schedulerConfig: any = schedulerConfig;
    private scheduler: Scheduler;

    columnLines = { disabled : false };
    stripe = { disabled : true };

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;

    ngAfterViewInit(): void {
        // Store Scheduler instance
        this.scheduler = this.schedulerComponent.instance;
    }

    handleToggle({ checked } : {checked : boolean}, feature : string): void {
        this[feature] = { disabled : !checked };
    }
}

<bryntum-demo-header
    link  = "../../../../../#example-frameworks-angular-basic"
></bryntum-demo-header>
<div class="demo-toolbar align-right">
    <bryntum-checkbox
        label="Stripe Feature"
        checked="false"
        (onAction)="handleToggle($event, 'stripe')"
    ></bryntum-checkbox>
    <bryntum-checkbox
        label="Column Lines Feature"
        checked="true"
        (onAction)="handleToggle($event, 'columnLines')"
    ></bryntum-checkbox>
</div>
<bryntum-scheduler
    #scheduler
    [barMargin]                 = "schedulerConfig.barMargin"
    [columns]                   = "schedulerConfig.columns"
    [endDate]                   = "schedulerConfig.endDate"
    [events]                    = "schedulerConfig.events"
    [mode]                      = "schedulerConfig.mode"
    [resourceImagePath]         = "schedulerConfig.resourceImagePath"
    [resources]                 = "schedulerConfig.resources"
    [resourceTimeRanges]        = "schedulerConfig.resourceTimeRanges"
    [resourceTimeRangesFeature] = "schedulerConfig.resourceTimeRangesFeature"
    [rowHeight]                 = "schedulerConfig.rowHeight"
    [startDate]                 = "schedulerConfig.startDate"
    [viewPreset]                = "schedulerConfig.viewPreset"
    [stripeFeature]             = "stripe"
    [columnLinesFeature]        = "columnLines"
></bryntum-scheduler>

// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/simple/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-simple"
        />
        <div class="demo-toolbar align-right">
            <bryntum-checkbox
                text="Stripe Feature"
                :checked="false"
                @action="handleToggle($event, 'stripe')"
            />
            <bryntum-checkbox
                text="Column Lines Feature"
                :checked="true"
                @action="handleToggle($event, 'columnLines')"
            />
        </div>
        <bryntum-scheduler
            ref="scheduler"
            v-bind="schedulerConfig"
            :stripeFeature="stripe"
            :columnLinesFeature="columnLines"
        />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumCheckbox
} from "@bryntum/scheduler-vue";
import { schedulerConfig } from "./AppConfig.js";

export default {
    name: "App",

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumCheckbox
    },

    methods: {
        handleToggle({ checked }, feature) {
            this[feature] = { disabled: !checked };
        }
    },

    data() {
        return {
            schedulerConfig,
            stripe: { disabled: true },
            columnLines: { disabled: false }
        };
    }
};
</script>

<style lang="scss">
@import "./App.scss";
</style>
