// scheduler-4.3.8-trial/examples/frameworks/react/javascript/drag-onto-tasks/src/App.js
/**
 * Application
 */
import React, { Fragment, useEffect, useState } from 'react';

import { BryntumDemoHeader, BryntumThemeCombo } from '@bryntum/scheduler-react';
import { AjaxStore, EventStore, Toast } from '@bryntum/scheduler/scheduler.umd';
import Scheduler from './components/Scheduler.js';
import Task from './lib/Task.js';
import EquipmentGrid from './lib/EquipmentGrid.js';
import './App.scss';

const App = () => {
    // we need to pass these three down to scheduler
    // useState prevents creating new instances on each run
    const [equipmentStore] = useState(
        new AjaxStore({
            modelClass: Task,
            readUrl: 'data/equipment.json',
            sorters: [{ field: 'name', ascending: true }]
        })
    );
    const [eventStore] = useState(
        new EventStore({
            modelClass: Task
        })
    );
    const [equipmentGrid] = useState(
        new EquipmentGrid({
            cls: 'equipment',
            eventStore: eventStore,
            // Use a chained Store to avoid its filtering to interfere with Scheduler's rendering
            store: equipmentStore.makeChained()
        })
    );
    useEffect(() => {
        equipmentGrid.appendTo = 'content';
        equipmentGrid.render();

        Toast.show({
            timeout: 3500,
            html:
                'Please note that this example uses the Bryntum Grid, which is licensed separately.'
        });
    }, [equipmentGrid]);

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-drag-onto-tasks"
                children={<BryntumThemeCombo />}
            />
            <div id="content">
                <Scheduler extraData={{ equipmentStore, EquipmentGrid, equipmentGrid }} />
            </div>
        </Fragment>
    );
};

export default App;

// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/drag-onto-tasks/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-drag-onto-tasks"
        />
        <div class="content-container">
            <bryntum-scheduler
                ref="scheduler"
                v-bind="schedulerConfig"
            />
            <grid ref="grid" :config="gridConfig"></grid>
        </div>
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/scheduler-vue/';
import { schedulerConfig, gridConfig } from './AppConfig.js';
import { Toast } from '@bryntum/scheduler';
import Grid from './components/Grid.vue';
import Drag from './lib/Drag.js';

export default {
    name: 'app',

    // Local components
    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        Grid
    },

    // Function that returns data
    data() {
        // console.log(schedulerConfig);
        return {
            schedulerConfig,
            gridConfig
        };
    },

    mounted() {
        const grid = this.$refs.grid.grid,
            schedule = this.$refs.scheduler.instance,
            outerElement = grid.element,
            equipmentStore = grid.store;
        new Drag({
            grid,
            schedule,
            outerElement
        });

        Toast.show({
            timeout: 3500,
            html:
                'Please note that this example uses the Bryntum Grid, which is licensed separately.'
        });

        schedule.equipmentStore = equipmentStore;
        schedule.onEquipmentStoreLoad =
            schedulerConfig.onEquipmentStoreLoad;

        schedule.equipmentStore.on(
            'load',
            schedule.onEquipmentStoreLoad.bind(schedule)
        );

        equipmentStore.load();
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
