// scheduler-4.3.8-trial/examples/frameworks/react/javascript/dependencies/src/App.js
/**
 * The App file. It should stay as simple as possible
 */
import React, { Fragment } from 'react';
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumThemeCombo
} from '@bryntum/scheduler-react';
import { schedulerConfig } from './AppConfig';
import './App.scss';

const App = () => {
    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-dependencies"
                children={<BryntumThemeCombo />}
            />
            <BryntumScheduler {...schedulerConfig} />
        </Fragment>
    );
};

export default App;

// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/localization/src/App.vue
<template>
    <div id="container">
        <bryntum-demo-header
            :title="$t('title')"
            link="../../../../../#example-frameworks-vue-javascript-localization"
        />
        <div class="demo-toolbar align-right">
            <locale-combo />
        </div>
        <bryntum-scheduler ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig.js';
import LocaleCombo from './components/LocaleCombo';

// import Bryntum locales
import './locales/index.js';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        LocaleCombo
    },

    data() {
        return {
            schedulerConfig
        };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
