// scheduler-4.3.8-trial/examples/frameworks/angular/angular-8/src/app/app.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { DateHelper,  Scheduler } from '@bryntum/scheduler/scheduler.lite.umd.js';
import AppEventModel from './lib/AppEventModel';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;

    schedulerConfig: any = schedulerConfig;

    // application properties
    scheduler: Scheduler;
    selectedEventName  = '';
    pickerDate = new Date(2018, 1, 7);
    barMargin = 5;

    ngAfterViewInit(): void {
        this.scheduler = this.schedulerComponent.instance;
    }

    //add event button click handled here
    onAddEventClick(): void {
        const { scheduler } = this;

        const event = new AppEventModel({
            resourceId   : scheduler.resourceStore.first.id,
            startDate    : scheduler.startDate,
            duration     : 2,
            durationUnit : 'h',
            name         : 'Meet CEO',
            desc         : 'Discuss project',
            eventType    : 'Meeting',
            eventColor   : 'red'
        });

        scheduler.editEvent(event);
    }

    //remove event button click handled here
    onRemoveEventClick(): void {
        const { scheduler } = this;
        scheduler.eventStore.remove(scheduler.selectedEvents);
    }

    onBarMarginChange({ value }): void {
        this.barMargin = value;
    }

    onEventSelectionChange(): void {
        if (this.scheduler.selectedEvents.length > 0) {
            this.selectedEventName = this.scheduler.selectedEvents[0].name;
        }
        else {
            this.selectedEventName = '';
        }
    }

    onReleaseEvent(): void {
        this.selectedEventName = '';
    }

    onDatePickerChange({ value }) : void {
        this.scheduler.setTimeSpan(
            DateHelper.add(value, 8, 'hour'),
            DateHelper.add(value, 18, 'hour')
        );
    }
}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-angular-8"
>
</bryntum-demo-header>
<div class = "demo-toolbar">
    <bryntum-button
        text = "Add event"
        icon = "b-fa b-fa-plus"
        cls = "b-green"
        (onClick) = "onAddEventClick()"
    ></bryntum-button>
    <bryntum-button
        text = "Remove event"
        icon = "b-fa b-fa-trash"
        cls = "b-red"
        (onClick) = "onRemoveEventClick()"
        [disabled] = "selectedEventName === ''"
    ></bryntum-button>
    <div class = "spacer"></div>
    <label class = "sel-event">
        Selected event:
        <span>{{ selectedEventName || 'None' }}</span>
    </label>
    <div class = "spacer"></div>
    <bryntum-date-field
        label = "Select date"
        [value] = "pickerDate"
        (onChange) = "onDatePickerChange($event)"
    ></bryntum-date-field>
    <bryntum-slider
        text = "Bar margin"
        min = 5
        max = 20
        [value] = "barMargin"
        (onInput) = "onBarMarginChange($event)"
    ></bryntum-slider>
</div>

<bryntum-scheduler
    #scheduler
    [barMargin] = "barMargin"
    [columns] = "schedulerConfig.columns"
    [crudManager] = "schedulerConfig.crudManager"
    [endDate] = "schedulerConfig.endDate"
    [eventEditFeature] = "schedulerConfig.eventEditFeature"
    [eventRenderer] = "schedulerConfig.eventRenderer"
    [events] = "schedulerConfig.events"
    [eventStore] = "schedulerConfig.eventStore"
    [resourceImagePath] = "schedulerConfig.resourceImagePath"
    [resources] = "schedulerConfig.resources"
    [rowHeight] = "schedulerConfig.rowHeight"
    [startDate] = "schedulerConfig.startDate"
    [timeRanges] = "schedulerConfig.timeRanges"
    [timeRangesFeature] = "schedulerConfig.timeRangesFeature"
    [viewPreset] = "schedulerConfig.viewPreset"
    (onEventSelectionChange) = "onEventSelectionChange()"
    (onReleaseEvent) = "onReleaseEvent()"
></bryntum-scheduler>

// scheduler-4.3.8-trial/examples/frameworks/react/typescript/basic/src/App.tsx
/**
 * Application
 */
import React, {
    Fragment,
    FunctionComponent,
    useEffect,
    useState,
    useRef,
    useCallback
} from 'react';
import {
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumScheduler,
    BryntumNumberField,
    BryntumButton
} from '@bryntum/scheduler-react';
import { Toast, EventModel } from '@bryntum/scheduler/scheduler.umd.js';
import axios from 'axios';
import { schedulerConfig } from './AppConfig';
import './App.scss';

const App: FunctionComponent = () => {
    const schedulerRef = useRef<typeof BryntumScheduler | null>(null);

    const [events, setEvents] = useState([]);
    const [resources, setResources] = useState([]);
    const [timeRanges, setTimeRanges] = useState([]);

    const [barMargin, setBarMargin] = useState(5);
    const [selectedEvent, setSelectedEvent] = useState<EventModel | null>(null);

    // load and set data
    useEffect(function() {
        axios
            .get('data/data.json')
            .then(response => {
                const { data } = response;
                setResources(data.resources.rows);
                setEvents(data.events.rows);
                setTimeRanges(data.timeRanges.rows);
            })
            .catch(error => {
                Toast.show(String(error));
                console.warn(error);
            });
    }, []);

    // event selection change handler
    const onEventSelectionChange = useCallback(({ selected }: { selected: EventModel[] }) => {
        setSelectedEvent(selected.length ? selected[0] : null);
    }, []);

    // add event handler
    const addEvent = useCallback(() => {
        const scheduler = schedulerRef.current.instance;
        const startDate = new Date(scheduler.startDate.getTime());
        const endDate = new Date(startDate.getTime());
        const resource = scheduler.resourceStore.first;

        if (!resource) {
            Toast.show('There is no resource available');
            return;
        }

        endDate.setHours(endDate.getHours() + 2);

        scheduler.eventStore.add({
            resourceId : resource.id,
            startDate  : startDate,
            endDate    : endDate,
            name       : 'New task',
            eventType  : 'Meeting'
        });
    }, []);

    // remove event handler
    const removeEvent = useCallback(() => {
        selectedEvent?.remove();
        setSelectedEvent(null);
    }, [selectedEvent]);

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-typescript-basic"
                children={<BryntumThemeCombo />}
            />
            <div className="demo-toolbar align-right">
                {(() => {
                    return selectedEvent ? (
                        <div className="selected-event">
                            <span>Selected event: </span>
                            <span>{selectedEvent.name}</span>
                        </div>
                    ) : (
                        ''
                    );
                })()}

                <BryntumNumberField
                    label="Bar margin"
                    min={0}
                    max={15}
                    value={barMargin}
                    onChange={({ value }: { value: number }) => setBarMargin(value)}
                />
                <BryntumButton icon="b-fa-plus" cls="b-green" onClick={addEvent} />
                <BryntumButton
                    icon="b-fa-trash"
                    cls="b-red"
                    onClick={removeEvent}
                    disabled={!selectedEvent}
                />
            </div>
            <BryntumScheduler
                ref={schedulerRef}
                {...schedulerConfig}
                events={events}
                resources={resources}
                timeRanges={timeRanges}
                barMargin={barMargin}
                onEventSelectionChange={onEventSelectionChange}
            />
        </Fragment>
    );
};

export default App;
