// scheduler-4.3.8-trial/examples/frameworks/angular/recurring-timeranges/src/app/app.component.ts
/**
 * App component script
 */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumButtonComponent, BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { Scheduler, DateHelper } from '@bryntum/scheduler/scheduler.lite.umd.js';
import { MyTimeRange } from './lib/MyTimeRange';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})

export class AppComponent implements AfterViewInit {

    public schedulerConfig = schedulerConfig;
    private scheduler: Scheduler;

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;
    @ViewChild(BryntumButtonComponent, { static : true }) coffeeButton: BryntumButtonComponent;

    /**
     * Runs after the view (including the child scheduler) is initializes
     */
    ngAfterViewInit(): void {
        this.scheduler = this.schedulerComponent.instance;
    }

    onCoffeeClick(): void {
        const coffee = this.scheduler.features.timeRanges.store.getById(1) as MyTimeRange;
        coffee.recurrenceRule = 'FREQ=WEEKLY;BYDAY=MO,TH;';
        this.coffeeButton.instance.disabled = true;
    }

    onPrevClick(): void {
        this.scheduler.shiftPrevious();
    }

    onTodayClick(): void {
        const today = DateHelper.clearTime(new Date());
        today.setHours(5);
        this.scheduler.setTimeSpan(today, DateHelper.add(today, 18, 'hour'));
    }

    onNextClick(): void {
        this.scheduler.shiftNext();
    }

    onStartClick(): void {
        this.scheduler.setTimeSpan(new Date(2019, 1, 7, 8), new Date(2019, 1, 29, 18));
    }
}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-recurring-timeranges"
>
</bryntum-demo-header>

<div class = "demo-toolbar">
    <bryntum-button
        #coffeeButton
        ref = 'coffeeButton'
        text = "More coffee"
        icon = 'b-fa-coffee'
        tooltip = 'Click to add morning coffee to Thursdays too'
        (onClick) = "onCoffeeClick()"
    ></bryntum-button>
    <div class = "spacer"></div>
    <bryntum-button
        ref = 'prevButton'
        icon = 'b-fa-angle-left'
        tooltip = 'View previous day'
        (onClick) = "onPrevClick()"
    ></bryntum-button>
    <bryntum-button
        ref = 'todayButton'
        text = 'Today'
        tooltip = 'View today, to see the current time line'
        (onClick) = "onTodayClick()"
    ></bryntum-button>
    <bryntum-button
        ref = 'nextButton'
        icon = 'b-fa-angle-right'
        tooltip = 'View next day'
        (onClick) = "onNextClick()"
    ></bryntum-button>
    <bryntum-button
        ref = 'startButton'
        text = 'Start'
        tooltip = 'Return to initial view'
        (onClick) = "onStartClick()"
    ></bryntum-button>
</div>

<bryntum-scheduler
    #scheduler
    [barMargin] = "schedulerConfig.barMargin"
    [eventStyle] = "schedulerConfig.eventStyle"
    [resourceImagePath] = "schedulerConfig.resourceImagePath"
    [timeRangesFeature] = "schedulerConfig.features.timeRanges"
    [columns] = "schedulerConfig.columns"
    [project] = "schedulerConfig.project"
    [crudManager] = "schedulerConfig.crudManager"
    [startDate] = "schedulerConfig.startDate"
    [endDate] = "schedulerConfig.endDate"
    [viewPreset] = "schedulerConfig.viewPreset"
></bryntum-scheduler>

// scheduler-4.3.8-trial/examples/frameworks/react/typescript/recurring-timeranges/src/App.tsx
/**
 * Application
 */
import React, { Fragment, FunctionComponent, useCallback, useRef } from 'react';

// our libraries
import { BryntumButton, BryntumDemoHeader, BryntumScheduler, BryntumThemeCombo } from '@bryntum/scheduler-react';

// application scss
import './App.scss';

// application files
import { schedulerConfig } from './AppConfig';
import { DateHelper } from "@bryntum/scheduler/scheduler.umd.js"
import { MyTimeRange } from "./lib/MyTimeRange"

const App: FunctionComponent = () => {
    const schedulerRef = useRef<typeof BryntumScheduler | null>(null);
    const coffeeButtonRef = useRef<typeof BryntumButton | null>(null);
    const scheduler = () => schedulerRef.current.instance;
    const coffeeButton = () => coffeeButtonRef.current.instance;

    const coffeeClickHandler = useCallback(() => {
        const coffee = scheduler().features.timeRanges.store.getById(1) as MyTimeRange;
        coffee.recurrenceRule = 'FREQ=WEEKLY;BYDAY=MO,TH;';
        coffeeButton().disabled = true;
    }, []);

    const prevClickHandler = useCallback(() => {
        scheduler().shiftPrevious();
    }, []);

    const nextClickHandler = useCallback(() => {
        scheduler().shiftNext();
    }, []);

    const todayClickHandler = useCallback(() => {
        const today = DateHelper.clearTime(new Date());
        today.setHours(5);
        scheduler().setTimeSpan(today, DateHelper.add(today, 18, 'hour'));
    }, []);

    const startClickHandler = useCallback(() => {
        scheduler().setTimeSpan(new Date(2019, 1, 7, 8), new Date(2019, 1, 29, 18));
    }, []);

    return (
        <Fragment>
            <BryntumDemoHeader
                href = "../../../../../#example-frameworks-react-typescript-recurring-timeranges"
                children = {<BryntumThemeCombo />}
            />
            <div className = "demo-toolbar">
                <BryntumButton
                    ref = {coffeeButtonRef}
                    text = "More coffee"
                    icon = 'b-fa-coffee'
                    tooltip = 'Click to add morning coffee to Thursdays too'
                    onClick = {coffeeClickHandler}
                />
                <div className = "spacer"></div>
                <BryntumButton
                    icon = 'b-fa-angle-left'
                    tooltip = 'View previous day'
                    onClick = {prevClickHandler}
                />
                <BryntumButton
                    text = 'Today'
                    tooltip = 'View today, to see the current time line'
                    onClick = {todayClickHandler}
                />
                <BryntumButton
                    icon = 'b-fa-angle-right'
                    tooltip = 'View next day'
                    onClick = {nextClickHandler}
                />
                <BryntumButton
                    text = 'Start'
                    tooltip = 'Return to initial view'
                    onClick = {startClickHandler}
                />
            </div>
            <BryntumScheduler ref = {schedulerRef} {...schedulerConfig} />
        </Fragment>
    );
};

export default App;
