// scheduler-4.3.8-trial/examples/frameworks/angular/angular-8/src/app/app.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { DateHelper,  Scheduler } from '@bryntum/scheduler/scheduler.lite.umd.js';
import AppEventModel from './lib/AppEventModel';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;

    schedulerConfig: any = schedulerConfig;

    // application properties
    scheduler: Scheduler;
    selectedEventName  = '';
    pickerDate = new Date(2018, 1, 7);
    barMargin = 5;

    ngAfterViewInit(): void {
        this.scheduler = this.schedulerComponent.instance;
    }

    //add event button click handled here
    onAddEventClick(): void {
        const { scheduler } = this;

        const event = new AppEventModel({
            resourceId   : scheduler.resourceStore.first.id,
            startDate    : scheduler.startDate,
            duration     : 2,
            durationUnit : 'h',
            name         : 'Meet CEO',
            desc         : 'Discuss project',
            eventType    : 'Meeting',
            eventColor   : 'red'
        });

        scheduler.editEvent(event);
    }

    //remove event button click handled here
    onRemoveEventClick(): void {
        const { scheduler } = this;
        scheduler.eventStore.remove(scheduler.selectedEvents);
    }

    onBarMarginChange({ value }): void {
        this.barMargin = value;
    }

    onEventSelectionChange(): void {
        if (this.scheduler.selectedEvents.length > 0) {
            this.selectedEventName = this.scheduler.selectedEvents[0].name;
        }
        else {
            this.selectedEventName = '';
        }
    }

    onReleaseEvent(): void {
        this.selectedEventName = '';
    }

    onDatePickerChange({ value }) : void {
        this.scheduler.setTimeSpan(
            DateHelper.add(value, 8, 'hour'),
            DateHelper.add(value, 18, 'hour')
        );
    }
}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-angular-8"
>
</bryntum-demo-header>
<div class = "demo-toolbar">
    <bryntum-button
        text = "Add event"
        icon = "b-fa b-fa-plus"
        cls = "b-green"
        (onClick) = "onAddEventClick()"
    ></bryntum-button>
    <bryntum-button
        text = "Remove event"
        icon = "b-fa b-fa-trash"
        cls = "b-red"
        (onClick) = "onRemoveEventClick()"
        [disabled] = "selectedEventName === ''"
    ></bryntum-button>
    <div class = "spacer"></div>
    <label class = "sel-event">
        Selected event:
        <span>{{ selectedEventName || 'None' }}</span>
    </label>
    <div class = "spacer"></div>
    <bryntum-date-field
        label = "Select date"
        [value] = "pickerDate"
        (onChange) = "onDatePickerChange($event)"
    ></bryntum-date-field>
    <bryntum-slider
        text = "Bar margin"
        min = 5
        max = 20
        [value] = "barMargin"
        (onInput) = "onBarMarginChange($event)"
    ></bryntum-slider>
</div>

<bryntum-scheduler
    #scheduler
    [barMargin] = "barMargin"
    [columns] = "schedulerConfig.columns"
    [crudManager] = "schedulerConfig.crudManager"
    [endDate] = "schedulerConfig.endDate"
    [eventEditFeature] = "schedulerConfig.eventEditFeature"
    [eventRenderer] = "schedulerConfig.eventRenderer"
    [events] = "schedulerConfig.events"
    [eventStore] = "schedulerConfig.eventStore"
    [resourceImagePath] = "schedulerConfig.resourceImagePath"
    [resources] = "schedulerConfig.resources"
    [rowHeight] = "schedulerConfig.rowHeight"
    [startDate] = "schedulerConfig.startDate"
    [timeRanges] = "schedulerConfig.timeRanges"
    [timeRangesFeature] = "schedulerConfig.timeRangesFeature"
    [viewPreset] = "schedulerConfig.viewPreset"
    (onEventSelectionChange) = "onEventSelectionChange()"
    (onReleaseEvent) = "onReleaseEvent()"
></bryntum-scheduler>

// scheduler-4.3.8-trial/examples/frameworks/react/javascript/simple/src/App.js
/**
 * The App contains Header and Scheduler components and makes them to work together
 */
import React, { Fragment, useState, useRef, useCallback } from 'react';
import { PropTypes } from 'prop-types';

import { Toast } from '@bryntum/scheduler/scheduler.umd';
import {
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumButton,
    BryntumNumberField,
    BryntumCheckbox
} from '@bryntum/scheduler-react';
import Scheduler from './components/Scheduler';
import Selected from './components/Selected';
import './App.scss';

const App = props => {
    // State
    const [barMargin, setBarMargin] = useState(props.defaultBarMargin);
    const [selectedEvent, setSelectedEvent] = useState('');
    const [columnLines, setColumnLines] = useState({ disabled: false });
    const [stripe, setStripe] = useState({ disabled: true });

    // Scheduler ref forwarded to Scheduler component
    const schedulerRef = useRef(null);

    /**
     * Show toast and set the selected event name.
     */
    const selectionChangeHandler = useCallback(({ selection }) => {
        const name = selection.length ? selection[0].name : '';
        const msg = name ? `You selected <b>${name}</b>` : 'All events are <b>deselected</b>';

        setSelectedEvent(name);
        Toast.show(msg);
    }, []);

    /**
     * Add an 1hr event for the first resource at the beginning of the scheduler
     */
    const addClickHandler = useCallback(
        event => {
            // Get the scheduler instance
            const scheduler = schedulerRef.current?.instance;

            if (!scheduler) {
                return;
            }

            // Get start and end date of the new event (1h duration)
            const startDate = new Date(scheduler.startDate.getTime()),
                endDate = new Date(startDate.getTime()),
                resource = scheduler.resourceStore.first;

            if (!resource) {
                Toast.show('There is no resource available');
                return;
            }

            endDate.setHours(endDate.getHours() + 1);

            // Gdd the event to the store
            scheduler.eventStore.add({
                resourceId: resource.id,
                startDate: startDate,
                endDate: endDate,
                name: 'New task',
                eventType: 'Meeting'
            });
        },
        [schedulerRef]
    );

    /**
     * Remove the selected event
     */
    const removeClickHandler = useCallback(
        event => {
            console.log('removeClickHandler', event);
            // Get the scheduler instance
            const scheduler = schedulerRef.current?.instance;

            if (!scheduler) {
                console.warn('Could not get Scheduler instance');
                return;
            }

            // Remove the selected event
            if (scheduler.selectedEvents.length) {
                scheduler.selectedEvents[0].remove();
            }

            setSelectedEvent('');
        },
        [schedulerRef]
    );

    // Header configuration
    const headerConfig = {
        href: '../../../../../#example-frameworks-react-javascript-simple'
    };

    // Scheduler configuration
    const schedulerConfig = {
        barMargin,
        onEventSelectionChange: selectionChangeHandler
    };

    return (
        <Fragment>
            <BryntumDemoHeader {...headerConfig} children={<BryntumThemeCombo />} />
            <div className="demo-toolbar align-right">
                <BryntumNumberField
                    label="Bar Margin:"
                    width={160}
                    min={0}
                    max={15}
                    step={1}
                    value={barMargin}
                    onChange={({ value }) => setBarMargin(value)}
                />
                <div className="spacer" />

                <BryntumCheckbox
                    label="Stripe Feature"
                    checked={false}
                    onAction={({ checked }) => setStripe({ disabled: !checked })}
                />
                <BryntumCheckbox
                    label="Column Lines Feature"
                    checked={true}
                    onAction={({ checked }) => setColumnLines({ disabled: !checked })}
                />
                <Selected selectedEvent={selectedEvent} />
                <BryntumButton
                    cls="b-green b-raised"
                    icon="b-fa b-fa-plus"
                    onClick={addClickHandler}
                />
                <BryntumButton
                    cls="b-red b-raised"
                    icon="b-fa b-fa-trash"
                    onClick={removeClickHandler}
                    disabled={!selectedEvent}
                />
            </div>
            <Scheduler
                {...schedulerConfig}
                columnLinesFeature={columnLines}
                stripeFeature={stripe}
                ref={schedulerRef}
            />
        </Fragment>
    );
};

App.propTypes = {
    defaultBarMargin: PropTypes.number
};

App.defaultProps = {
    defaultBarMargin: 5
};

export default App;
