// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/vue-renderer/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-vue-renderer"
        />
        <bryntum-scheduler v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumDemoHeader,
    BryntumScheduler
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig';

export default {
    name: 'App',

    components: {
        BryntumScheduler,
        BryntumDemoHeader
    },

    data() {
        return { schedulerConfig };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// scheduler-4.3.8-trial/examples/frameworks/react/javascript/drag-between-schedulers/src/App.js
/**
 * The App file. It should stay as simple as possible
 */
import React, { Fragment } from 'react';

import { BryntumDemoHeader, BryntumThemeCombo } from '@bryntum/scheduler-react';
import Content from './components/Content.js';
import './App.scss';

const App = props => {
    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-drag-between-schedulers"
                children={<BryntumThemeCombo />}
            />
            <Content />
        </Fragment>
    );
};

export default App;
