// scheduler-4.3.8-trial/examples/frameworks/angular/custom-event-editor/src/app/app.component.ts
/**
 * Application component
 */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatDialog, MatDialogConfig } from '@angular/material/dialog';
import { EventEditorComponent } from './event-editor/event-editor.component';
import { BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { Scheduler } from '@bryntum/scheduler/scheduler.lite.umd.js';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})

export class AppComponent implements AfterViewInit {
    schedulerConfig: any = schedulerConfig;

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;
    private scheduler: Scheduler;

    constructor(public editor: MatDialog) { }

    beforeEventEdit(event: any): boolean {
        const
            { eventRecord, resourceRecord, eventEdit } = event,
            editorConfig = new MatDialogConfig();

        Object.assign(editorConfig, {
            disableClose : false,
            autoFocus    : true,
            width        : '500px',
            data         : {
                eventRecord,
                resourceRecord,
                eventStore : eventEdit.eventStore
            }
        });

        // console.log('data=', editorConfig.data);
        this.editor.open(EventEditorComponent, editorConfig);

        // suppress default event editor
        return false;
    }

    ngAfterViewInit(): void {
        // Store Scheduler instance
        this.scheduler = this.schedulerComponent.instance;
        // install beforeEventEdit listener
        this.scheduler.on('beforeEventEdit', this.beforeEventEdit.bind(this));
    }

    /**
     * Custom event renderer for the scheduler
     */
    eventRenderer = ({ eventRecord }: { eventRecord: any }): string => {
        return `
            <div class="info">
                <div class="name">${eventRecord.name}</div>
                <div class="desc">${eventRecord.desc}</div>
            </div>
        `;
    }

}

<bryntum-demo-header
    link  = "../../../../../#example-frameworks-angular-custom-event-editor"
></bryntum-demo-header>

<bryntum-scheduler
    #scheduler
    [barMargin]         = "schedulerConfig.barMargin"
    [columns]           = "schedulerConfig.columns"
    [crudManager]       = "schedulerConfig.crudManager"
    [endDate]           = "schedulerConfig.endDate"
    [eventEditFeature]  = "schedulerConfig.eventEditFeature"
    [eventRenderer]     = "eventRenderer"
    [eventStyle]        = "schedulerConfig.eventStyle"
    [resourceImagePath] = "schedulerConfig.resourceImagePath"
    [rowHeight]         = "schedulerConfig.rowHeight"
    [startDate]         = "schedulerConfig.startDate"
    [viewPreset]        = "schedulerConfig.viewPreset"
></bryntum-scheduler>

// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/custom-event-editor/src/App.vue
<!-- Application -->
<template>
    <v-app>
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-custom-event-editor"
        />
        <bryntum-scheduler
            ref="scheduler"
            v-bind="schedulerConfig"
            :listeners="listeners"
        />
        <event-editor
            v-model="showEditor"
            :eventRecord="eventRecord"
            :eventStore="eventStore"
            :resourceId="resourceId"
            @close="onCloseEditor"
        />
    </v-app>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig';
import EventEditor from './components/EventEditor.vue';

export default {
    name: 'App',

    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        EventEditor
    },

    data() {
        return {
            schedulerConfig,
            showEditor  : false,
            eventRecord : null,
            eventStore  : null,
            resourceId  : null,
            listeners   : {
                beforeEventEdit : this.beforeEventEditHandler
            }
        };
    },

    methods: {
        beforeEventEditHandler(event) {
            this.openEditor(event);
            return false;
        },

        openEditor({ source, resourceRecord, eventRecord }) {
            Object.assign(this, {
                eventStore: source.eventStore,
                resourceId: resourceRecord.id,
                eventRecord: eventRecord,
                showEditor: true
            });
        },

        onCloseEditor() {
            const scheduler = this.$refs.scheduler.instance;
            if (scheduler) {
                scheduler.refresh();
            }
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
