// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/vue-renderer/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-vue-renderer"
        />
        <bryntum-scheduler v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumDemoHeader,
    BryntumScheduler
} from '@bryntum/scheduler-vue';
import { schedulerConfig } from './AppConfig';

export default {
    name: 'App',

    components: {
        BryntumScheduler,
        BryntumDemoHeader
    },

    data() {
        return { schedulerConfig };
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// scheduler-4.3.8-trial/examples/frameworks/react/typescript/recurring-events/src/App.tsx
/**
 * Application
 */
import React, { FunctionComponent, Fragment } from 'react';

// our libraries
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumThemeCombo
} from '@bryntum/scheduler-react';

// application scss
import './App.scss';

// application files
import { schedulerConfig } from './AppConfig';

const App: FunctionComponent = () => {
    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-typescript-recurring-events"
                children={<BryntumThemeCombo />}
            />
            <BryntumScheduler {...schedulerConfig} />
        </Fragment>
    );
};

export default App;
