// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/animations/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-animations"
        />
        <div class="demo-toolbar">
            <bryntum-slider
                text="Animation duration"
                v-bind="sliderConfig"
                @change="sliderChangeHandler"
            ></bryntum-slider>
            <bryntum-button text="Max 1hr" @click="maxHandler"></bryntum-button>
            <bryntum-button text="Move to after lunch" @click="moveHandler"></bryntum-button>
            <bryntum-button text="Random update" @click="randomHandler"></bryntum-button>
        </div>

        <bryntum-scheduler ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumButton,
    BryntumSlider
} from '@bryntum/scheduler-vue';
import { DateHelper } from '@bryntum/scheduler';
import { schedulerConfig, sliderConfig } from './AppConfig';

export default {
    name: 'App',
    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumButton,
        BryntumSlider
    },

    data() {
        return { schedulerConfig, sliderConfig, scheduler: null };
    },

    mounted() {
        // save bryntum scheduler instance for easier access in methods
        this.$data.scheduler = this.$refs.scheduler.instance;

        // set the default animation duration
        this.changeDuration(600);
    },

    methods: {
        sliderChangeHandler({ value }) {
            this.changeDuration(value);
        },

        // set time of all Meetings to max 1 hour
        maxHandler() {
            const {
                scheduler: { eventStore }
            } = this;
            eventStore
                .query(task => task.eventType === 'Meeting')
                .forEach(task => (task.duration = Math.min(task.duration, 1)));
        },

        // moves events of type "Meeting" after lunch
        moveHandler() {
            const {
                scheduler,
                scheduler: { eventStore }
            } = this;
            if (scheduler.features) {
                const lunchFinishTime = scheduler.features.timeRanges.store.getById('lunch')
                    .endDate;
                eventStore
                    .query(task => task.eventType === 'Meeting')
                    .forEach(
                        task =>
                            (task.startDate = DateHelper.max(task.startDate, lunchFinishTime))
                    );
            }
        },

        // randomizes the events
        randomHandler() {
            const {
                scheduler,
                scheduler: { eventStore }
            } = this;
            const indices = [];
            const nbrToAnimate = Math.min(eventStore.count, 4);

            // Grab a bunch of random events to change
            while (indices.length < nbrToAnimate) {
                const index = Math.floor(Math.random() * eventStore.count);

                if (!indices.includes(index)) {
                    indices.push(index);
                }
            }
            indices.forEach(index => {
                const ev = eventStore.getAt(index);

                if (ev && ev.resource) {
                    ev.beginBatch();
                    ev.resourceId =
                        ((scheduler.resourceStore.indexOf(ev.resource) + 2) % 8) + 1;
                    ev.setStartDate(
                        DateHelper.add(
                            ev.startDate,
                            ev.startDate.getHours() % 2 ? 1 : -1,
                            'hour'
                        ),
                        true
                    );
                    ev.endBatch();
                }
            });
        },

        // handle animation duration change
        changeDuration(value) {
            const scheduler = this.$refs.scheduler.instance;
            let styleNode = this.styleNode;

            if (!styleNode) {
                styleNode = this.styleNode = document.createElement('style');
                document.head.appendChild(styleNode);
            }

            scheduler.transitionDuration = value;
            styleNode.innerHTML = `.b-grid-row,.b-sch-event-wrap { transition-duration: ${value /
                1000}s !important; }`;
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>

// scheduler-4.3.8-trial/examples/frameworks/react/javascript/animations/src/App.js
/**
 * The App file. It should stay as simple as possible
 */
import React, { Fragment, useCallback, useEffect, useRef, useState } from 'react';

import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumThemeCombo,
    BryntumSlider,
    BryntumButton
} from '@bryntum/scheduler-react';
import { DomHelper, DateHelper } from '@bryntum/scheduler/scheduler.umd';
import { schedulerConfig, sliderConfig } from './AppConfig';
import './App.scss';

const App = () => {
    const schedulerRef = useRef(null);
    const [duration, setDuration] = useState(600);

    /**
     * Gets the styleNode from the head. Creates if it does not exist.
     */
    const getStyleNode = useCallback(() => {
        const styleNode =
            DomHelper.getElement('style#duration') ||
            DomHelper.append(document.head, {
                id: 'duration',
                tag: 'style'
            });
        return styleNode;
    }, []);
    const [styleNode] = useState(getStyleNode());

    /**
     * Sets the animation duration both in scheduler and in
     * the page head in styleNode
     */
    useEffect(() => {
        schedulerRef.current.instance.transitionDuration = duration;
        styleNode.innerHTML = `.b-grid-row,.b-sch-event-wrap { transition-duration: ${
            duration / 1000
        }s !important; }`;
    }, [duration, styleNode]);

    /**
     * Reshuffles some events randomly.
     */
    const randomClickHandler = useCallback(() => {
        const scheduler = schedulerRef.current.instance,
            eventStore = scheduler.eventStore,
            indices = [];

        // Grab a bunch of random events to change
        while (indices.length < 4) {
            const index = Math.floor(Math.random() * eventStore.count);

            if (!indices.includes(index)) {
                indices.push(index);
            }
        }
        indices.forEach(index => {
            const ev = eventStore.getAt(index);

            if (ev && ev.resource) {
                ev.beginBatch();
                ev.resourceId = ((scheduler.resourceStore.indexOf(ev.resource) + 2) % 8) + 1;
                ev.setStartDate(
                    DateHelper.add(ev.startDate, ev.startDate.getHours() % 2 ? 1 : -1, 'hour'),
                    true
                );
                ev.endBatch();
            }
        });
    }, []);

    /**
     * Resizes some events to be max 1 hour long.
     */
    const maxClickHandler = useCallback(() => {
        schedulerRef.current.instance.eventStore
            .query(task => task.eventType === 'Meeting')
            .forEach(task => (task.duration = Math.min(task.duration, 1)));
    }, []);

    /**
     * Moves some events to after lunch time.
     */
    const moveClickHandler = useCallback(() => {
        const scheduler = schedulerRef.current.instance;
        const eventStore = scheduler.eventStore;
        const lunchFinishTime = scheduler.features.timeRanges.store.getById('lunch').endDate;
        eventStore
            .query(task => task.eventType === 'Meeting')
            .forEach(
                task => (task.startDate = DateHelper.max(task.startDate, lunchFinishTime))
            );
    }, []);

    return (
        <Fragment>
            <BryntumDemoHeader
                href="../../../../../#example-frameworks-react-javascript-animations"
                children={<BryntumThemeCombo />}
            />
            <div className="demo-toolbar">
                <BryntumSlider
                    {...sliderConfig}
                    value={duration}
                    onChange={({ value }) => setDuration(value)}
                />
                <BryntumButton text="Max 1hr" onClick={maxClickHandler} />
                <BryntumButton text="Move to after lunch" onClick={moveClickHandler} />
                <BryntumButton text="Random update" onClick={randomClickHandler} />
            </div>
            <BryntumScheduler ref={schedulerRef} {...schedulerConfig} />
        </Fragment>
    );
};

export default App;
