// scheduler-4.3.8-trial/examples/frameworks/angular/animations/src/app/app.component.ts
/**
 * App component script
 */
import { AfterViewInit, Component, OnInit, ViewChild } from '@angular/core';
import { BryntumSchedulerComponent } from '@bryntum/scheduler-angular';
import { DateHelper, Menu, Scheduler, TimeSpan } from '@bryntum/scheduler/scheduler.lite.umd.js';
import AppEventModel from './lib/AppEventModel';
import { schedulerConfig } from './app.config';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})

export class AppComponent implements OnInit, AfterViewInit {

    public schedulerConfig = schedulerConfig;
    private styleNode: HTMLStyleElement = document.createElement('style');
    private scheduler: Scheduler;

    @ViewChild(BryntumSchedulerComponent, { static : true }) schedulerComponent: BryntumSchedulerComponent;

    /**
     * Runs after the view (including the child scheduler) is initializes
     */
    ngAfterViewInit(): void {
        this.scheduler = this.schedulerComponent.instance;
        this.setAnimationDuration(600);
    }

    /**
     * Runs on this component initialization
     */
    ngOnInit(): void {
        document.head.appendChild(this.styleNode);
    }

    /**
     * Sets the duration of animation.
     */
    setAnimationDuration(value: number): void {
        this.scheduler.transitionDuration = value;
        this.styleNode.innerHTML = `.b-grid-row,.b-sch-event-wrap { transition-duration: ${value / 1000}s !important; }`;
    }

    /**
     * Initial animation button click handler
     */
    onInitialAnimation = ({ source }) => {
        const { scheduler } = this;

        function play(animation: any) {
            scheduler.restartInitialAnimation(animation);
        }

        new Menu({
            forElement  : source.element,
            closeAction : 'destroy',
            width       : source.element.offsetWidth,
            items       : [
                {
                    text     : 'Fade in',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'fade-in',
                    onItem   : () => play('fade-in')
                },
                {
                    text     : 'Slide from left',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'slide-from-left',
                    onItem   : () => play('slide-from-left')
                },
                {
                    text     : 'Slide from top',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'slide-from-top',
                    onItem   : () => play('slide-from-top')
                },
                {
                    text     : 'Zoom in',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'zoom-in',
                    onItem   : () => play('zoom-in')
                },
                {
                    text     : 'Custom',
                    icon     : 'b-fa b-fa-play',
                    cls      : 'b-separator',
                    disabled : scheduler.useInitialAnimation === 'custom',
                    onItem   : () => play('custom')
                }
            ],
            listeners : {
                destroy() {
                    source.pressed = false;
                }
            }
        });
    }

    /**
     * Random update button click handler
     */
    onRandomUpdate = () => {
        const
            { scheduler } = this,
            eventStore = scheduler.eventStore,
            indices = [],
            nbrToAnimate = Math.min(eventStore.count, 4);

        // Grab a bunch of random events to change
        while (indices.length < nbrToAnimate) {
            const index = Math.floor(Math.random() * eventStore.count);

            if (!indices.includes(index)) {
                indices.push(index);
            }
        }
        indices.forEach((index) => {
            const ev: any = eventStore.getAt(index);

            if (ev && ev.resource) {
                ev.beginBatch();
                ev.resourceId = (scheduler.resourceStore.indexOf(ev.resource) + 2) % 8 + 1;
                ev.setStartDate(DateHelper.add(ev.startDate, ev.startDate.getHours() % 2 ? 1 : -1, 'hour'), true);
                ev.endBatch();
            }
        });

    }

    /**
     * After lunch button click handler. Moves all meetings after lunch.
     */
    onAfterLunch(): void {
        const
            { scheduler } = this,
            eventStore = scheduler.eventStore,
            lunchFinishTime = (scheduler.features.timeRanges.store.getById('lunch') as TimeSpan).endDate;

        eventStore.query((event: AppEventModel) => event.eventType === 'Meeting')
            .forEach((event: AppEventModel) => event.startDate = DateHelper.max(event.startDate as Date, lunchFinishTime as Date));

    }

    /**
     * Max 1 hr button click handler. Resizes all Meeting to be max 1 hr long.
     */
    onMaxHour(): void {
        const { scheduler } = this;
        scheduler.eventStore.query((event: AppEventModel) => event.eventType === 'Meeting')
            .forEach((event: AppEventModel) => event.duration = Math.min(event.duration, 1));
    }

    /**
     * Duration slider change handler
     */
    onDurationChange({ value }): void {
        this.setAnimationDuration(value);
    }

}

<bryntum-demo-header
    link = "../../../../../#example-frameworks-angular-animations"
>
</bryntum-demo-header>

<div class = "demo-toolbar">
    <bryntum-button
        text = "Max 1hr"
        (onClick) = "onMaxHour()"
    ></bryntum-button>
    <bryntum-button
        text = "After lunch"
        (onClick) = "onAfterLunch()"
    ></bryntum-button>
    <bryntum-button
        text = "Random update"
        (onClick) = "onRandomUpdate()"
    ></bryntum-button>
    <bryntum-button
        text = "Initial animation"
        icon = "b-fa b-fa-sliders-h"
        toggleable = "true"
        (onClick) = "onInitialAnimation($event)"
    ></bryntum-button>
    <div class = "spacer"></div>
    <bryntum-slider
        text = "Animation duration"
        [max] = 3000
        [min] = 0
        [step] = 200
        [value] = 600
        (onChange) = "onDurationChange($event)"
    ></bryntum-slider>
</div>

<bryntum-scheduler
    #scheduler
    [barMargin] = "schedulerConfig.barMargin"
    [columns] = "schedulerConfig.columns"
    [crudManager] = "schedulerConfig.crudManager"
    [endDate] = "schedulerConfig.endDate"
    [eventColor] = "schedulerConfig.eventColor"
    [resourceImagePath] = "schedulerConfig.resourceImagePath"
    [rowHeight] = "schedulerConfig.rowHeight"
    [startDate] = "schedulerConfig.startDate"
    [timeRangesFeature] = "schedulerConfig.timeRangesFeature"
    [useInitialAnimation] = "schedulerConfig.useInitialAnimation"
    [viewPreset] = "schedulerConfig.viewPreset"
></bryntum-scheduler>

// scheduler-4.3.8-trial/examples/frameworks/vue/javascript/animations/src/App.vue
<!-- Application -->
<template>
    <div id="container">
        <bryntum-demo-header
            link="../../../../../#example-frameworks-vue-javascript-animations"
        />
        <div class="demo-toolbar">
            <bryntum-slider
                text="Animation duration"
                v-bind="sliderConfig"
                @change="sliderChangeHandler"
            ></bryntum-slider>
            <bryntum-button text="Max 1hr" @click="maxHandler"></bryntum-button>
            <bryntum-button text="Move to after lunch" @click="moveHandler"></bryntum-button>
            <bryntum-button text="Random update" @click="randomHandler"></bryntum-button>
        </div>

        <bryntum-scheduler ref="scheduler" v-bind="schedulerConfig" />
    </div>
</template>

<script>
import {
    BryntumScheduler,
    BryntumDemoHeader,
    BryntumButton,
    BryntumSlider
} from '@bryntum/scheduler-vue';
import { DateHelper } from '@bryntum/scheduler';
import { schedulerConfig, sliderConfig } from './AppConfig';

export default {
    name: 'App',
    components: {
        BryntumDemoHeader,
        BryntumScheduler,
        BryntumButton,
        BryntumSlider
    },

    data() {
        return { schedulerConfig, sliderConfig, scheduler: null };
    },

    mounted() {
        // save bryntum scheduler instance for easier access in methods
        this.$data.scheduler = this.$refs.scheduler.instance;

        // set the default animation duration
        this.changeDuration(600);
    },

    methods: {
        sliderChangeHandler({ value }) {
            this.changeDuration(value);
        },

        // set time of all Meetings to max 1 hour
        maxHandler() {
            const {
                scheduler: { eventStore }
            } = this;
            eventStore
                .query(task => task.eventType === 'Meeting')
                .forEach(task => (task.duration = Math.min(task.duration, 1)));
        },

        // moves events of type "Meeting" after lunch
        moveHandler() {
            const {
                scheduler,
                scheduler: { eventStore }
            } = this;
            if (scheduler.features) {
                const lunchFinishTime = scheduler.features.timeRanges.store.getById('lunch')
                    .endDate;
                eventStore
                    .query(task => task.eventType === 'Meeting')
                    .forEach(
                        task =>
                            (task.startDate = DateHelper.max(task.startDate, lunchFinishTime))
                    );
            }
        },

        // randomizes the events
        randomHandler() {
            const {
                scheduler,
                scheduler: { eventStore }
            } = this;
            const indices = [];
            const nbrToAnimate = Math.min(eventStore.count, 4);

            // Grab a bunch of random events to change
            while (indices.length < nbrToAnimate) {
                const index = Math.floor(Math.random() * eventStore.count);

                if (!indices.includes(index)) {
                    indices.push(index);
                }
            }
            indices.forEach(index => {
                const ev = eventStore.getAt(index);

                if (ev && ev.resource) {
                    ev.beginBatch();
                    ev.resourceId =
                        ((scheduler.resourceStore.indexOf(ev.resource) + 2) % 8) + 1;
                    ev.setStartDate(
                        DateHelper.add(
                            ev.startDate,
                            ev.startDate.getHours() % 2 ? 1 : -1,
                            'hour'
                        ),
                        true
                    );
                    ev.endBatch();
                }
            });
        },

        // handle animation duration change
        changeDuration(value) {
            const scheduler = this.$refs.scheduler.instance;
            let styleNode = this.styleNode;

            if (!styleNode) {
                styleNode = this.styleNode = document.createElement('style');
                document.head.appendChild(styleNode);
            }

            scheduler.transitionDuration = value;
            styleNode.innerHTML = `.b-grid-row,.b-sch-event-wrap { transition-duration: ${value /
                1000}s !important; }`;
        }
    }
};
</script>

<style lang="scss">
@import './App.scss';
</style>
